### ISSUE TITLE
Monitoring DaemonSet  metrics: Error display metrics

### ISSUE THREAD

**Issue by wirwolf** [rancher/charts#1939] opened 2022-06-14 11:48 UTC
When i deploy Redis with equals name in a two different namespace and open metric in another DaemonSet deployment
![Screenshot_20220614_143324](https://user-images.githubusercontent.com/8457572/173569471-9b672896-7edc-4e12-83ce-92b5371f032e.png)

**Comment by aiyengar2** [comment] 2022-10-27 00:22
dupe of https://github.com/rancher/rancher/issues/39430

**Closed by aiyengar2** 2022-10-27 00:22 UTC
Labels: [zube]: To Triage
