### ISSUE TITLE
OpenEBS Error: failed parsing --set data: key

### ISSUE THREAD

**Issue by codejamninja** [rancher/charts#268] opened 2019-10-11 20:13 UTC
I am getting the following error in the OpenEBS chart. I think it has something to do with the escaped commas in the questions.yaml file.

```
2019/10/11 20:08:54 [ERROR] AppController p-cm6sn/openebs [helm-controller] failed with : wait helm template failed. Error: failed parsing --set data: key "fd0\\" has no value (cannot end with ,)
: exit status 1
2019/10/11 20:08:54 [ERROR] AppController p-cm6sn/openebs [helm-controller] failed with : wait helm template failed. Error: failed parsing --set data: key "OpenEBS" has no value (cannot end with ,)
: exit status 1
```

**Comment by guangbochen** [comment] 2019-10-18 02:41
duplicate of https://github.com/rancher/rancher/issues/23534, will close it in here.

**Closed by guangbochen** 2019-10-18 02:41 UTC
