### ISSUE TITLE
no template "grafana.fullname" associated with template "gotpl"

### ISSUE THREAD

**Issue by jouve** [rancher/charts#1205] opened 2021-05-17 18:44 UTC
upgrade to monitoring chart version 14.5.100 fails with this error :
```
---------------------------------------------------------------------
--
SUCCESS:  helm upgrade --history-max=5 --install=true  --namespace=cattle-monitoring-system --timeout=10m0s  --values=/home/shell/helm/values-rancher-monitoring-crd-14.5.100.yaml  --version=14.5.100 --wait=true rancher-monitoring-crd  /home/shell/helm/rancher-monitoring-crd-14.5.100.tgz
---------------------------------------------------------------------
helm  upgrade --history-max=5 --install=true  --namespace=cattle-monitoring-system --timeout=10m0s  --values=/home/shell/helm/values-rancher-monitoring-14.5.100.yaml  --version=14.5.100 --wait=true rancher-monitoring  /home/shell/helm/rancher-monitoring-14.5.100.tgz
Error:  UPGRADE FAILED: template:  rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml:117:13:  executing  "rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml" at  &lt;include "call-nested" (list . "grafana" "grafana.fullname")&gt;:  error calling include: template:  rancher-monitoring/templates/_helpers.tpl:21:4: executing "call-nested"  at &lt;include $template (dict "Chart" (dict "Name" (last $subchart))  "Values" $values "Release" $dot.Release "Capabilities"  $dot.Capabilities)&gt;: error calling include: template: no template  "grafana.fullname" associated with template "gotpl"
--
```

**Comment by devops-leni** [comment] 2021-06-11 09:04
Hello,

I have the same issue with the chart version 14.5.100 but only when I want to disable the Grafana !

My values file : 
```
grafana:
  enable: false

prometheus:
  prometheusSpec:
    evaluationInterval: 1m
    retentionSize: ${prometheus_retention_size}GiB
    scrapeInterval: 1m
    replicas: ${prometheus_replicas}
    resources:
     ...

rkeControllerManager:
  enabled: true

rkeEtcd:
  enabled: true

rkeProxy:
  enabled: true

rkeScheduler:
  enabled: true
```

The error after the helm upgrade log : 
```
Error: template: rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml:117:13: 
executing "rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml" 
at <include "call-nested" (list . "grafana" "grafana.fullname")>: 
error calling include: template: rancher-monitoring/templates/_helpers.tpl:21:4: 
executing "call-nested" at <include $template (dict "Chart" (dict "Name" (last $subchart)) 
"Values" $values "Release" $dot.Release "Capabilities" $dot.Capabilities)>: 
error calling include: template: no template "grafana.fullname" associated with template "gotpl"
```

**Comment by evoicefire** [comment] 2021-07-01 05:41
I am also having the same issue when trying to disable grafana. Same output as above.

**Comment by nickvth** [comment] 2021-07-08 07:57
+1

**Comment by fplantinga-guida** [comment] 2021-07-08 08:49
Experiencing the same issue. I even tried uninstalling and reinstalling. I guess the issue is related to the grafana dependency in this chart.

**Comment by MKlimuszka** [comment] 2022-08-30 21:16
Issue moved to [rancher/rancher #38780](https://github.com/rancher/rancher/issues/38780) via [**ZenHub**](https://www.zenhub.com/)

**Comment by aiyengar2** [comment] 2022-10-18 16:58
Duplicate of https://github.com/rancher/rancher/issues/39090, closing this issue out.

**Closed by aiyengar2** 2022-10-18 16:58 UTC
Labels: internal, kind/bug, [zube]: Team Area 3
