### ISSUE TITLE
rancher-monitoring: alertmanager-rancher-monitoring-alertmanager does not get updated when values.yaml have changed

### ISSUE THREAD

**Issue by domruf** [rancher/charts#1819] opened 2022-03-22 16:47 UTC
When installing rancher-monitoring and later upgrading with different values for .Values.alertmanager.config these changes have no effect.

The template checks if the secret already exists, and if so it will not be overwritten.
https://github.com/rancher/charts/blob/75e5ca5b24d60d9448a544ba91345edb6910f68b/charts/rancher-monitoring/100.1.1%2Bup19.0.3/templates/alertmanager/secret.yaml#L4

But as a use who has changed .Values.alertmanager.config, I expect these changes to be reflected after calling ```helm upgrade```.

I'm also wondering about the reasons for [```"helm.sh/resource-policy": keep```.](https://github.com/rancher/charts/blob/75e5ca5b24d60d9448a544ba91345edb6910f68b/charts/rancher-monitoring/100.1.1%2Bup19.0.3/templates/alertmanager/secret.yaml#L13)
When the config from values.yaml is used, I think the secret should be deleted on uninstall.

The resource-policy means that even after uninstalling rancher-monitoring the new .Values.alertmanager.config will have no effect when (re-)installing.

**Comment by danragnar** [comment] 2022-04-14 07:28
I'm having the same issue. It seems counter-intuitive to me only modify/create the alertmanager secret on install. This would mean that you would have to delete the secret everytime you want to change the config? kube-prometheus-stack does not do this, so why would rancher-monitoring?

**Comment by danragnar** [comment] 2022-04-14 07:49
It's the same thing with the rancher-alerting-drivers/prom2teams configmap btw. Is there a good reason for it to not update the configmap on helm upgrade?

**Comment by lucasscheepers** [comment] 2022-05-04 10:52
I'm facing the same issue... Could you please explain further the workaround you are talking about? @danragnar @domruf

**Comment by lucasscheepers** [comment] 2022-05-05 20:02
Well I deleted the `alertmanager` secret and tried to do a clean install with the helm chart, but that didn't work either (explained in [this Stackoverflow post](https://stackoverflow.com/questions/72115324/alertmanager-configuration-does-not-get-updated-when-values-yml-have-changed)). Hopefully you can help me a bit further?

**Comment by aiyengar2** [comment] 2022-10-27 00:10
The logic for this is described in our docs: https://docs.ranchermanager.rancher.io/how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager#multiple-alertmanager-replicas

```
By default, the Alertmanager Config Secret created by Rancher will never be modified or deleted on an upgrade or uninstall of the rancher-monitoring chart. This restriction prevents users from losing or overwriting their alerting configuration when executing operations on the chart.
```

This was an intentional decision made for the Rancher Monitoring chart to prevent user alerting configuration loss on an uninstall. Also, since we expose a UI for managing the alertmanager secret outside of Helm (which does not exist with the kube-prometheus-stack chart, since it is just a chart), we did not want to manage the secret via Helm (which would require a helm upgrade of the **entire** chart every time you wanted to do something like add a receiver).

Either way, with the latest versions of Monitoring we should be moving towards using the new Alertmanager custom resources exposed by Prometheus Operator around Alertmanager configuration.

**Closed by aiyengar2** 2022-10-27 00:10 UTC
Labels: [zube]: To Triage

**Comment by nskumz** [comment] 2023-01-24 14:36
By default, the Alertmanager Config Secret created by Rancher will **never be modified or deleted** on an upgrade or uninstall of the rancher-monitoring chart. This restriction prevents users from losing or overwriting their alerting configuration when executing operations on the chart.
then how will we edit the secret i am confused

**Comment by brandongallagher1999** [comment] 2023-05-16 15:54
This issue should NOT be closed. I can not get my alert manager instance to get a custom configuration. It just looks at `alertmanager.yaml.gz` and generates its config from there. Deleting the secret doesn't work. This bug has been delaying our prod deployment for 3+ days.

**Comment by funilrys** [comment] 2023-05-19 09:24
Agree. I'm using Fleet - by myself - to manage our clusters and I thought I could update our hooks - centrally - and no ... I have to update them manually ... 

cc: @aiyengar2

**Comment by tjanson** [comment] 2023-08-08 14:19
This issue still persists. Yes, it would be nice to use the Alertmanager CRD -- but `rancher-monitoring` does not do so, yet.

So for the time being you have a configuration values that's effectively "write-once". The worst part is that the user gets no direct feedback when changing the values and attempting to deploy them, they're simply silently ignored.

> we did not want to manage the secret via Helm (which would require a helm upgrade of the entire chart every time you wanted to do something like add a receiver)

But you *are* managing the secret via Helm. (Which is fine, that's how plenty of charts do things.) You're just not updating it.

This unexpected behavior should be mentioned prominently in the docs, e.g., in the [values file section](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/102.0.2%2Bup40.1.2/values.yaml#L807-L809), possibly in the [README](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/102.0.2%2Bup40.1.2/README.md), not just in [the template](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/102.0.2%2Bup40.1.2/templates/alertmanager/secret.yaml#L1-L4) (where one eventually ends up after debugging the issue).

_If_ this is desired behavior (I would hope not), then this is an unresolved documentation issue.

**Comment by fabiorauber** [comment] 2023-08-28 17:43
It is common for Helm charts to manage Secrets and ConfigMaps in cases like this and they usually instruct the user to make the changes in values.yaml file of the Helm release instead of doing it directly. The current state of things is counter intuitive and I was also wondering for a couple of hours what was going wrong until I found this issue...
