### ISSUE TITLE
[charts/kafka] External broker access

### ISSUE THREAD

**Issue by matthax** [rancher/charts#87] opened 2018-12-13 17:37 UTC
After reading through the [documentation](https://github.com/rancher/charts/tree/master/charts/kafka/v0.7.3#connecting-to-kafka-from-outside-kubernetes) about connecting to Kafka externally I am still unable to find any success.

I have tried manually editing the YAML file in Rancher but the values are being mangled/incorrectly interpreted after saving.

I've tried a whole bunch of different formats and templates but have had no success.

```
configurationOverrides.advertised.listeners: "EXTERNAL://kafka.ebiapps.comcast.com:$((31090 + ${KAFKA_BROKER_ID}))"
```
I've tried setting the listeners property
```configurationOverrides.listeners: "{PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092}"```

I've also reviewed similar issues
 - https://github.com/helm/charts/issues/9310
 - https://github.com/helm/charts/issues/9062

![screen shot 2018-12-13 at 12 36 48 pm](https://user-images.githubusercontent.com/12008400/49956673-cadf8180-fed3-11e8-9212-09b714a51bf7.png)

Could you provide a concrete example/documentation for configuring the Kafka chart for external access?

**Comment by shdowofdeath** [comment] 2018-12-26 06:38
Hi @matthax  could you please share the steps to reproduce it, something like 
file that you are using ( helm chart ) including values files that you are using?

**Comment by mayankkapoor** [comment] 2019-04-03 07:00
Same issue here while trying to deploy kafka helm chart on minikube.

**Comment by deniseschannon** [comment] 2022-01-07 21:30
This repo was originally providing the Helm 2 charts in the "Library" catalog in Rancher in our original UI in the `master` branch. This UI was deprecated in Rancher 2.6 and the charts in them are no longer maintained. 

This repo is now serving the Rancher charts in the new Apps and Marketplace in our new UI that was introduced in Rancher 2.5. These new Helm 3 charts are in the `dev-*` and `release-*` are the ones that are being actively maintained by the Rancher team. 

Partner charts are now maintained in a different repo: rancher/partner-charts.

Due to these changes, this issue will be closed as it is referencing our old charts that aren't being updated.

**Closed by deniseschannon** 2022-01-07 21:30 UTC
Labels: kind/question, status/investigate
