### ISSUE TITLE
[Rancher Monitoring] API Server availability metrics not working with Kubernetes 1.23

### ISSUE THREAD

**Issue by moray95** [rancher/charts#2043] opened 2022-08-24 14:10 UTC
Since upgrading our cluster to Kubernetes 1.23 from 1.22, API Server availability metrics stopped working. `apiserver_request:availability30d{verb="write"}` and `apiserver_request:availability30d{verb="all"}` metrics are no longer present. `apiserver_request:availability30d{verb="read"}` seems to work fine. This causes the API Server Grafana dashboard not being able to display overall and read availability as well as ErrorBudget. Error budget related alerts are also unable to fire properly.

After some digging, I think I found the issue. Recording rules for `all` and `write` verbs use `apiserver_request_duration_seconds{le="40"}` [metric here](https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring/100.1.2%2Bup19.0.3/templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml#L59) . However, in 1.23, the 40 bucket has been removed. See the related changelog [here](https://github.com/kubernetes/kubernetes/blob/776cff391524478b61212dbb6ea48c58ab4359e1/CHANGELOG/CHANGELOG-1.23.md#other-cleanup-or-flake-1). Changing the 40 bucket to 30 or 45 should fix the issue.

**Comment by aiyengar2** [comment] 2022-10-27 00:25
I think the root cause of this issue was addressed in https://github.com/rancher/rancher/issues/37778, the actual computation of the synthetic series apiserver_request:availability30d was fixed in https://github.com/rancher/charts/pull/2162/commits/427adae9685d2e4427c8698d00fa6afe8e9eea7c

Closing in favor of the root issue

**Closed by aiyengar2** 2022-10-27 00:25 UTC
