### ISSUE TITLE
Gatekepper 3.12 OOB release into 2.7

### ISSUE THREAD

**Issue by rohitsakala** [rancher/charts#2594] opened 2023-05-03 00:56 UTC
PR merged into Dev https://github.com/rancher/charts/pull/2574

**Comment by rohitsakala** [comment] 2023-05-16 17:30
Waiting for QA

**Comment by vivek-shilimkar** [comment] 2023-05-24 04:48
Duplicate of the issue in rancher/rancher hence closing. - https://github.com/rancher/rancher/issues/41625

**Closed by vivek-shilimkar** 2023-05-24 04:48 UTC
Labels: [zube]: To Test, team/mapps, team/infracloud
